name: School Timetable Bot

on:
  schedule:
    # 한국 시간 기준 아침 08:10 (UTC 23:10)
    # 월~금 아침마다 실행됩니다.
    - cron: '22 16 * * 0-4' 
  workflow_dispatch: # 지금 바로 실행해볼 수 있는 버튼 생성

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # v4로 업데이트해서 노란 경고 제거
      - name: Set up Python
        uses: actions/setup-python@v5 # v5로 업데이트해서 노란 경고 제거
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Bot
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python '찐찐최종.py' # 따옴표 안에 파일 이름을 정확히 넣었습니다.
